Repository artsalliancemedia/thunderstorm-library, pull requests merged in 2019-06, with the labels that each got.

#61 Handle errors
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: reviewed-approved

#62 [feature] add custom metrics labeller
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: reviewed-approved

#63 Fix/exception catching
  test/test_kafka_messaging.py
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: reviewed-approved, bug, release

#65 [fix] increase broker_request_timeout to 90
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: unreviewed, bug

#66 [fix] add statsd metric pattern for kafka errors
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: reviewed-approved

#67 Sentry
  requirements.txt
  test/test_kafka_messaging.py
  thunderstorm/__init__.py
  thunderstorm/kafka_messaging.py
Labels: PR: reviewed-approved, release
